### ISSUE TITLE
1.0 beta checklist

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#2223]
List of 1.0 BC: https://github.com/angular-ui/ui-router/issues/2219

# Blockers

## Merge

- [ ] #1585 Sort url rules by specificity (Add to BC list)
- [ ] 48aeaff6 *(maybe)* Investigate if we should keep the "avoid-url-resync-after-transition" code
- [ ] f9b43d66833f0e17de41fd8d1cc3b491e3ba4a0e *(maybe)* Figure out if/where $viewContentLoading goes in new architecture
- [x] 02e98660a80dfd1ca4b113dd24ee304af91e9f8c path parameter slash encoding/decoding
- [x] 77fa11bf0787d0f6da97ab0003ab29afb7411391 squash trailing slash for optional params
- [x] 20d6e243f1745ddbf257217245a1dc22eabe13da proper default value for array query param
- [x] 3831af1dc71b601351e6694af0665a77297f8f7f ui-state directive 
- [x] a9ff6febb469e0d5cd49054216c4472df7a6259d ng-class syntax for ui-sref-active
- [x] 9dc31c5465328e5666468b0c2319ce205f4b72f8
- [x] e40102492d40fe1cf6ba14d955fcc9f345c16458 Allow `params: { foo: { type: "int" } }`
- [x] 6a371f9b70e37a82eb324122879e4473c3f6d526 Fix param type configuration rule
- [x] b5130bb1215e15f832ea6daa670410b9a950c0d4 recognize squashed url properly
- [x] d31b3337cc2ce71d87c92fdded629e46558d0b49 dots in url
- [x] 9dc31c5465328e5666468b0c2319ce205f4b72f8 ui-sref fix
- [x] 7c914030f13e05e45a941c1b723cb785db729890 ui-sref fix
- [x] c219e801797f340ef9c5c919ab890ef003a7a042 $sniffer pushstate detection
- [x] 9b6d9a2d0ce4ae08384165cb517bddea59b67892 animate ng1.4 compat
- [x] 1be13795686ab78abb2d5094bc8addcacb928975 animate fix
- [x] 3d7f267bee14 ui-sref-active + eq on same el
- [x] c4fec8c7998113902af4152d716c42dada6eb465 prototypal inherit state.data
- [x] a1f07559ec74e10ff80bc4be81f287e3772b8fcb `options` for $stateChange* events
- [x] 71d7469987ee9ca86a41c8c6393ccd5d8913c3d6 add params to isState filter
- [x] 4b7f304617f0b3590b532103b5c2fb526c98a9e4 allow spaces in url params
- [x] Merge in anything else committed to  https://github.com/angular-ui/ui-router/commits/master/src/stateDirectives.js
- [x] Find remaining commits from 0.2.11 through 0.2.16 that should be merged to 1.0

## Bugs

https://github.com/angular-ui/ui-router/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A1.0

# Features

- [x] Retain resolved data during transition redirect 
- [x] Consolidate StateParams and ParamValues classes
- [x] Baked in redirectTo processing, as an `onStart` hook #948
- [x] Add/remove states during runtime (stateRegistry.ts)
- [x] Earlier exit hook than onExit... maybe integrate with `onBefore` afcfe959e29af51977c23106ebf80812022e44f3
  - should fire before an onStart hook that redirects if a user is not authenticated, for example);
  -  Better integration with view code (controller/component).
- [x] Make path parameters non-optional by default (add to *BC*)

# Chores

## branches, repositories, orgs

- [x] Create separate repo for ui-router-core
- [x] Branch angular-ui/ui-router `master` to `0.2.x`
- [x] Merge (or move?) `feature-1.0` to `master`
- [x] Move core code to ui-router-core
- [x] Release first version of ui-router-core 
- [x] Import ui-router-core into angular-ui-router
- [x] Release angular-ui-router beta
- [x] Release ui-router-ng2 alpha
- [x] Find a home for ui-router StateVis and TransitionVis
- [x] Find a home for new demo app

##  common.ts

 - [x] Remove unused code from common

## TS and ES6

 - [x] Ensure tslint passes rules
 - [ ] Configure build with tslint
 - [x] ES6ify remaining ES5 classes

# Non-Blockers

(but will block a release candidate)

## Docs

 - [x] docs -- update for http://typedoc.io docs generation
 - [ ] recipes and approaches
 - [x] interactive architecture overview (statevis/transitionvis)
 - [x] Add lots of docs and comments to the new demo app

**Comment by nateabele** [comment]
@wesleycho @christopherthielen What would some alternatives to ng-docs be?

**Comment by christopherthielen** [comment]
I do not know, but there's gotta be something out there that does something cool with typescript

**Comment by nateabele** [comment]
[This](http://typedoc.io/) looks pretty.

**Comment by royaldark** [comment]
@christopherthielen Will the `ui-state` directive be available in an upcoming 0.2.x release, or only in 1.0?

**Comment by nateabele** [comment]
@royaldark Both.

**Comment by areologist** [comment]
@nateabele Can I be of any assistance with respect to the `ui-state` merge or other 1.0 items?

**Comment by christopherthielen** [comment]
Yes feel free to do the ui-state merge!

**Comment by areologist** [comment]
Thanks, Chris.  I just started a new job but I'll start on this soon.

**Comment by eeelated** [comment]
@christopherthielen Does the 1.0 version already support parallel state? I have a project that has a great need of parallel state. And how close is 1.0? I'm not familiar with things enough to understand what the checklist items are:). I can help with testing 1.0 against an existing application though, and would also love to help with any simple tasks from the checklist.

**Comment by nateabele** [comment]
> Does the 1.0 version already support parallel state?

Not yet unfortunately.

> And how close is 1.0?

Very close. Helping with the issues on this list will make it closer. Testing against existing apps is also important.

**Comment by atian25** [comment]
any time plan for 1.x publish ?

**Comment by christopherthielen** [comment]
I'd like to get beta out this week.  there are going to be a few breaking changes between alpha and beta.  We'll let it bake for a few weeks.  if all goes well, then I think we're ready for a final release.
